### PR TITLE
Add another key ldap group to list

### PR DESCRIPTION
**Pull request by hwine**
real change is at line 61 (added vpn_tooltooleditor). Not sure what happened to white space.

### CODE REVIEW

**Comment by escapewindow** [comment]
@hwine do we still want this?

**Comment by tomprince** [comment]
Even if we do, it is out-of-date since at least https://bugzilla.mozilla.org/show_bug.cgi?id=1605448

**Comment by hwine** [comment]
> 
> 
> @hwine do we still want this?

*/me retrieves context from Glacier*

The intent of the transitioning doc is to cover all special permissions that need to be added (and thus removed) when someone joins (leaves) the team.  If there are special permission w.r.t. tooltool, then they should be listed.

Since Tom notes the process has changed, it's probably best to open a new PR (after checking if some other update didn't add it already).

**Review by catlee — COMMENTED** [review]
We probably don't need this any more :)

**Comment by escapewindow** [comment]
Hi Catlee!

**Comment by MihaiTabara** [comment]
> We probably don't need this any more :)

Aloha :)

**Comment by catlee** [comment]
Ohai :)

**Comment by sylvestre** [comment]
Salut!

**Comment by hwine** [comment]
@catlee are you really missing triaging bugs? 😂 Best wishes!

**Pull request closed without merging**
