### PR TITLE
Setup 'sphinx-autobuild' as the recommended development workflow

### PR DESCRIPTION
**Pull request by ahal**

### CODE REVIEW

**Comment by escapewindow** [comment]
Nice, thank you!

https://github.com/mozilla/build-relengdocs/blob/main/maintaining_these_docs.rst#maintaining-this-documentation is now no longer accurate, and we do get the warning `/Users/asasaki/src/releng/relengdocs/README.md: WARNING: document isn't included in any toctree` when running `make livehtml`.

Can/should we solve these two things with one change?

**Comment by ahal** [comment]
Thanks for pointing that out, I never realized that file existed.. The content of both files is almost the same, so would be good to consolidate IMO. Maybe we can add the README to the toctree where `maintaining_these_docs` used to be so the instructions show up both in the repo and in the generated docs?

**Comment by escapewindow** [comment]
> Thanks for pointing that out, I never realized that file existed.. The content of both files is almost the same, so would be good to consolidate IMO. Maybe we can add the README to the toctree where `maintaining_these_docs` used to be so the instructions show up both in the repo and in the generated docs?

Sounds perfect.

**Review by escapewindow — APPROVED** [review]
🎉

**Comment by ahal** [comment]
Neat, readthedocs is now building on my PRs whereas before it wasn't for some reason..

**Pull request merged**
