### PR TITLE
fix warnings + green up rtd build

### PR DESCRIPTION
**Pull request by escapewindow**
- RTD builds are currently busted on funcparserlib, for some reason.
- Funcparserlib is pulled in from sphinx-actdiag.
- release_workflows/fx_ga_release is the only page that uses actdiag.
- release_workflows is a fairly old and out of date set of pages.

To solve the busted RTD builds, I'm removing sphinx-actdiag as a dep,
and the `release_workflows/` directory as well. Also fixing warnings.

### CODE REVIEW

**Comment by escapewindow** [comment]
[Green build!](https://readthedocs.org/projects/moz-releng-docs/builds/)

**Review by moz-releng-automation-stage — APPROVED** [review]

**Review by bhearsum — APPROVED** [review]

**Comment by ahal** [comment]
Nice! Is there a way to turn the build orange if we introduce new warnings? Might be good to set up to prevent further regressions there.

**Comment by escapewindow** [comment]
I'm not sure how we can get RTD reporting here: possibly adding a token? I hesitated to do that with my account, since I have access to many things. Are you familiar with RTD setup @ahal ? I think I can give you access to the RTD account if you don't already have it through Github.

**Comment by ahal** [comment]
Oh right, I forgot there's no local sphinx build happening here (like there is in m-c). I'm not aware of any readthedocs reporting, I guess we'd have to stand up a task that generates the docs directly. Maybe that would be worth the effort? Not sure.

**Pull request merged**
